
spring:
  application:
    name: olivers
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/elliot?useUnicode=true&characterEncoding=utf8
    username: root
    password: dge_1992@163.com
