

#rocketmq??
rocketmq:
  topic: springboot-mq
  name-server: 10.211.55.4:9876
  producer:
    # ??????????????group?????
    group: rocketmq-pro-group
    # ????????,??3000
    sendMessageTimeout: 3000
    # ?????????????2
    retryTimesWhenSendFailed: 2
    # ???????????2
    retryTimesWhenSendAsyncFailed: 2
    # ?????? ??1024*4(4M)
    maxMessageSize: 4096
    # ???????????????broker???false
    retryNextServer: false
    # ?????????4k(1024 * 4)
    compressMessageBodyThreshold: 4096
  consumer:
    group: rocketmq-consumer-group

