

spring:
  redis:
    host:
    port: 6000

server:
  port: 8090

# Actuator模块
management:
  endpoints:
    # http访问模式
    web:
      exposure:
        # 暴露端点
        include: '*'
        # 不暴露端点
        exclude:
      # 自定义监控路径
      base-path: /dgeActuator
  endpoint:
    # health端点
    health:
      # 公开信息程度
      show-details: always
    # shutdown端点
    shutdown:
      # 是否开启 http://localhost:8080/dgeActuator/shutdown Post
      enabled: true
    # beans端点
    beans:
      cache:
        # 缓存10秒
        time-to-live: 10s
  health:
    mongo:
      # 禁用mongo的健康检测
      enabled: false
