server:
  port: 8081


rocketmq:
  topic: springboot-mq
  name-server: 10.211.55.4:9876
  producer:
    group: rocketmq-pro-group
    sendMessageTimeout: 3000
    retryTimesWhenSendFailed: 2
    retryTimesWhenSendAsyncFailed: 2
    maxMessageSize: 4096
    retryNextServer: false
    compressMessageBodyThreshold: 4096
  consumer:
    group: CONSUMER_TEST_GROUP