

server:
  port: 8090

# logging.pattern.console: 设置日志打印格式
# logging.path: 设置日志输出路径
# logging.file: 设置日志输出文件名称
# logging.path 和 logging.file冲突，logging.file级别高
# logging.level:日志打印级别

# logging:
  # pattern:
    # console: "%d{yyyy/MM/dd-HH:mm:ss} [%X{TRACE_LOG_ID}] [%thread] %-5level %logger- %msg%n"
  # path: /Users/apple/Documents/workspace/github/springboot-demo/log
  # file: logTest
  # level:
    # root: error
    # com.github.dge1992.log.LogApplicationTests: warn



#  自定义日志配置
#  根据不同的日志系统，你可以按如下规则组织配置文件名，就能被正确加载：
#
#  Logback：logback-spring.xml, logback-spring.groovy, logback.xml, logback.groovy
#  Log4j：log4j-spring.properties, log4j-spring.xml, log4j.properties, log4j.xml
#  Log4j2：log4j2-spring.xml, log4j2.xml
#  JDK (Java Util Logging)：logging.properties