
server:
  port: 9099

rest:
  auth-open: true #是否开启jwt token认证
  sign-open: true #是否开启签名验签

jwt:
  header: Authorization   #http\u8BF7\u6C42\u5934\u6240\u9700\u8981\u7684\u5B57\u6BB5
  secret: mySecret        #jwt\u79D8\u94A5
  expiration: 604800      #7\u5929 \u5355\u4F4D:\u79D2
  auth-path: auth         #\u8BA4\u8BC1\u8BF7\u6C42\u7684\u8DEF\u5F84
  md5-key: randomKey      #md5\u52A0\u5BC6\u6DF7\u6DC6key

