server:
  port: 8081


rocketmq:
  topic: springboot-mq
  name-server: 10.211.55.4:9876
  producer:
    group: rocketmq-pro-group
    sendMessageTimeout: 3000
    retryTimesWhenSendFailed: 2
    retryTimesWhenSendAsyncFailed: 2
    maxMessageSize: 4096
    retryNextServer: false
    compressMessageBodyThreshold: 4096
  consumer:
    group: CONSUMER_TEST_GROUP

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elliot?useUnicode=true&characterEncoding=utf8
    username: root
    password: dge_1992@163.com