
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://47.99.62.141:3306/home?useSSL=false&allowMultiQueries=true
    username: root
    password: fnn@520dge
    filters: log4j,wall,mergeStat

mybatis-plus:
  mapper-locations:  classpath:mappers/*.xml
  typeAliasesPackage: com.github.dge1992.mybatis.domain
  global-config:
    id-type: 0  #0:\u6570\u636E\u5E93ID\u81EA\u589E   1:\u7528\u6237\u8F93\u5165id  2:\u5168\u5C40\u552F\u4E00id(IdWorker)  3:\u5168\u5C40\u552F\u4E00ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #\u914D\u7F6E\u7684\u7F13\u5B58\u7684\u5168\u5C40\u5F00\u5173
    lazyLoadingEnabled: true #\u5EF6\u65F6\u52A0\u8F7D\u7684\u5F00\u5173
    multipleResultSetsEnabled: true

logging:
  level:
    com.github.dge1992: debug
