
server:
  port: 8090

spring:
  multi-datasource:
    open: false # 是否开启多数据源
  basic: # 基本数据源
    datasource:
      url: jdbc:mysql://39.105.12.20:9000/test?useSSL=false&allowMultiQueries=true
      username: root
      password: 123
      filters: log4j,wall,mergeStat
      validation-query: SELECT 'x'
  second: # 第二个数据库
    datasource:
      # url: jdbc:oracle:thin:@hdoracle.dev.200jit.com:1521:nboffice
      url: jdbc:oracle:thin:@116.62.68.192:1521:hddb
      username: modelhome
      password: oracle_modelhome
      filters: log4j,wall,mergeStat
      driver-class-name: oracle.jdbc.driver.OracleDriver
      validation-query: SELECT * from dual #{oracle: SELECT * from dual} {mysql: SELECT 'x'}

mybatis-plus:
  mapper-locations:  classpath:mappers/*.xml
  typeAliasesPackage: com.github.dge1992.mybatis.domain
  global-config:
    id-type: 0  #0:数据库ID自增   1:该类型为未设置主键类型  2:该类型可以通过自己注册自动填充插件进行填充  3:全局唯一ID
    db-column-underline: false
    refresh-mapper: true
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true # 是否开启自动驼峰命名规则
    cache-enabled: true # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    lazyLoadingEnabled: true # 懒加载
    multipleResultSetsEnabled: true

logging:
  level:
    com.github.dge1992: debug #\u5F00\u542F\u6253\u5370sql\u8BED\u53E5
