
server:
  port: 8090

spring:
  datasource:
    url: jdbc:oracle:thin:@hdoracle.dev.200jit.com:1521:nboffice
    username: modelhome
    password: oracle_modelhome
    filters: log4j,wall,mergeStat

mybatis-plus:
  mapper-locations:  classpath:mappers/*.xml
  typeAliasesPackage: com.github.dge1992.mybatis.domain
  global-config:
    id-type: 0  #0:\u6570\u636E\u5E93ID\u81EA\u589E   1:\u7528\u6237\u8F93\u5165id  2:\u5168\u5C40\u552F\u4E00id(IdWorker)  3:\u5168\u5C40\u552F\u4E00ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    db-config:
      logic-delete-value: 1 # \u903B\u8F91\u5DF2\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 1)
      logic-not-delete-value: 0 # \u903B\u8F91\u672A\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 0)
  configuration:
    map-underscore-to-camel-case: true # \u662F\u5426\u5F00\u542F\u81EA\u52A8\u9A7C\u5CF0\u547D\u540D\u89C4\u5219
    cache-enabled: true #\u914D\u7F6E\u7684\u7F13\u5B58\u7684\u5168\u5C40\u5F00\u5173
    lazyLoadingEnabled: true #\u5EF6\u65F6\u52A0\u8F7D\u7684\u5F00\u5173
    multipleResultSetsEnabled: true

logging:
  level:
    com.github.dge1992: debug #\u5F00\u542F\u6253\u5370sql\u8BED\u53E5
